import { Store } from '../types/store'

export const DUMMY_STORES: Store[] = [
  {
    id: '1',
    name: '복실 잡화점',
    category: '생활·서비스',
    subCategory: '잡화 · 생활',
    hours: '10:00~21:00',
    description:
      '전통시장 최고의 잡화점입니다. 다양한 생활용품이 준비되어 있습니다.',
    isFood: false,
    tags: ['생활용품', '가성비', '친절한'],
    info: '중앙 통로 15번 건물 · 10:00 ~ 21:00\n일요일 휴무 · 02-123-4567',
    rating: 4.5,
    badgeText: '잡',
    imageUrl:
      'https://images.unsplash.com/photo-1542838132-92c53300491e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: '2',
    name: '복실 잡화점 2호점',
    category: '생활·서비스',
    subCategory: '잡화 · 생활',
    hours: '10:00~21:00',
    description: '생활용품과 잡화를 전문으로 판매하는 복실잡화점 2호점입니다.',
    isFood: false,
    tags: ['생활용품', '다양한'],
    info: '중앙 통로 16번 건물 · 10:00 ~ 21:00\n연중무휴 · 02-123-4568',
    rating: 4.6,
    badgeText: '잡',
  },
  {
    id: '3',
    name: '대박 수산',
    category: '수산·정육',
    subCategory: '수산물 · 활어회',
    hours: '09:00~20:00',
    description: '매일 아침 산지직송되는 신선한 활어와 해산물이 가득합니다.',
    isFood: true,
    tags: ['신선함', '회포장', '매운탕'],
    menus: [
      { name: '광어/우럭 세트 (소)', price: '25,000원' },
      { name: '모듬회 (중)', price: '40,000원' },
      { name: '제철 대하구이', price: '20,000원' },
    ],
    info: '서문 입구 3번 통로 · 09:00 ~ 20:00\n월요일 휴무 · 02-987-6543',
    rating: 4.8,
    badgeText: '수',
  },
  {
    id: '4',
    name: '시골 떡집',
    category: '떡·빵·간식',
    subCategory: '간식 · 전통 떡',
    hours: '08:00~20:00',
    description: '국산 쌀로 빚어 쫄깃하고 달콤한 전통 떡 전문점입니다.',
    isFood: true,
    tags: ['쫄깃쫄깃', '선물세트', '국산쌀'],
    menus: [
      { name: '인절미 (1팩)', price: '3,000원' },
      { name: '영양찰떡', price: '3,500원' },
      { name: '꿀떡 (1팩)', price: '3,000원' },
    ],
    info: '남문 1번 출구 인근 · 08:00 ~ 20:00\n연중무휴 · 02-456-7890',
    rating: 4.7,
    badgeText: '떡',
  },
  {
    id: '5',
    name: '엄마 손맛 반찬',
    category: '반찬·식재료',
    subCategory: '반찬 · 김치',
    hours: '09:00~21:00',
    description: '조미료 없이 건강하게 만든 엄마의 손맛 반찬입니다.',
    isFood: true,
    tags: ['엄마손맛', '집반찬', '조미료무첨가'],
    menus: [
      { name: '포기김치 (1kg)', price: '12,000원' },
      { name: '밑반찬 3종 세트', price: '10,000원' },
      { name: '소고기 장조림', price: '7,000원' },
    ],
    info: '중앙광장 동측 골목 · 09:00 ~ 21:00\n매주 일요일 휴무 · 02-567-8901',
    rating: 4.9,
    badgeText: '반',
  },
  {
    id: '6',
    name: '새마을 정육점',
    category: '수산·정육',
    subCategory: '정육 · 한우/한돈',
    hours: '09:00~21:00',
    description: '최고급 한우와 한돈만을 엄선하여 정직한 무게로 판매합니다.',
    isFood: false,
    tags: ['한우', '삼겹살', '진공포장'],
    info: '북문 2번 통로 코너 · 09:00 ~ 21:00\n연중무휴 · 02-234-5678',
    rating: 4.7,
    badgeText: '정',
  },
  {
    id: '7',
    name: '싱싱 야채과일',
    category: '농산물',
    subCategory: '농산물 · 과일/채소',
    hours: '08:00~20:00',
    description:
      '산지에서 직송된 신선한 채소와 제철 과일을 저렴하게 만나보세요.',
    isFood: false,
    tags: ['제철과일', '유기농채소', '신선도보장'],
    info: '남문 중앙 통로 7호 · 08:00 ~ 20:00\n연중무휴 · 02-345-6789',
    rating: 4.4,
    badgeText: '농',
  },
  {
    id: '8',
    name: '만나 분식',
    category: '음식',
    subCategory: '음식 · 분식',
    hours: '10:00~22:00',
    description:
      '매콤달콤한 쌀떡볶이와 바삭한 수제 튀김이 있는 전통 분식집입니다.',
    isFood: true,
    tags: ['떡볶이', '수제튀김', '가성비맛집'],
    menus: [
      { name: '쌀떡볶이', price: '4,000원' },
      { name: '모듬튀김 (5개)', price: '4,500원' },
      { name: '찰순대', price: '4,000원' },
    ],
    info: '중앙 통로 22번 상점 · 10:00 ~ 22:00\n매주 화요일 휴무 · 02-765-4321',
    rating: 4.8,
    badgeText: '음',
  },
  {
    id: '9',
    name: '영이네 옷방',
    category: '의류',
    subCategory: '의류 · 여성의류',
    hours: '10:00~20:00',
    description: '세련되고 편안한 여성 의류와 패션 잡화 편집숍입니다.',
    isFood: false,
    tags: ['여성의류', '데일리룩', '편안한옷'],
    info: '서문 패션거리 12호 · 10:00 ~ 20:00\n일요일 휴무 · 02-876-5432',
    rating: 4.3,
    badgeText: '의',
  },
  {
    id: '10',
    name: '광장 호떡집',
    category: '떡·빵·간식',
    subCategory: '간식 · 호떡',
    hours: '11:00~21:00',
    description: '겉은 바삭하고 속은 달콤한 꿀이 가득한 전통 찹쌀 호떡입니다.',
    isFood: true,
    tags: ['꿀호떡', '찹쌀호떡', '시장별미'],
    menus: [
      { name: '찹쌀 꿀호떡', price: '1,500원' },
      { name: '씨앗 야채호떡', price: '2,000원' },
      { name: '부산 어묵 (1개)', price: '1,000원' },
    ],
    info: '중앙광장 사거리 리어카 매대 · 11:00 ~ 21:00\n재료 소진 시 조기 마감 · 010-1234-5678',
    rating: 4.9,
    badgeText: '간',
  },
  {
    id: '11',
    name: '원조 가마솥 통닭',
    category: '음식',
    subCategory: '음식 · 치킨',
    hours: '12:00~23:00',
    description: '가마솥에서 튀겨내어 더욱 바삭하고 담백한 옛날 통닭입니다.',
    isFood: true,
    tags: ['옛날통닭', '가마솥치킨', '바삭한겉바속촉'],
    menus: [
      { name: '가마솥 옛날통닭 (1마리)', price: '9,000원' },
      { name: '순살 닭강정 (대)', price: '15,000원' },
      { name: '양념통닭 (1마리)', price: '12,000원' },
    ],
    info: '북문 먹자골목 4호 · 12:00 ~ 23:00\n매주 월요일 휴무 · 02-432-1098',
    rating: 4.7,
    badgeText: '음',
  },
  {
    id: '12',
    name: '동해 건어물',
    category: '수산·정육',
    subCategory: '수산물 · 건어물',
    hours: '09:00~20:00',
    description:
      '동해 청정 해역에서 건조한 최상급 멸치, 오징어, 황태 전문점입니다.',
    isFood: false,
    tags: ['국물용멸치', '맥주안주오징어', '설선물'],
    info: '동문 건어물 거리 2호 · 09:00 ~ 20:00\n연중무휴 · 02-543-2109',
    rating: 4.5,
    badgeText: '수',
  },
]
