import { Store } from '../types/store'

export const DUMMY_STORES: Store[] = [
  // ═══ 블록 1 ═══
  {
    id: '1',
    name: 'BGT소금빵',
    category: '떡·빵·간식',
    subCategory: '소금빵',
    hours: '10:00~20:00',
    description: '겉바속촉 갓 구워낸 맛있는 소금빵 전문점입니다.',
    isFood: true,
    tags: ['소금빵', '디저트', '베이커리'],
    menus: [
      { name: '소금빵 (1개)', price: '3,000원' },
      { name: '앙버터 소금빵', price: '4,000원' },
      { name: '소금빵 러스크', price: '3,500원' },
    ],
    info: '1블록 좌측외열 1번 · 10:00 ~ 20:00',
    rating: 4.8,
    badgeText: '빵',
    block: 1,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '2',
    name: '모두뼈다귀',
    category: '음식',
    subCategory: '감자탕',
    hours: '11:00~22:00',
    description: '푸짐한 양과 진한 국물이 일품인 감자탕 전문점입니다.',
    isFood: true,
    tags: ['감자탕', '뼈다귀', '식사'],
    menus: [
      { name: '뼈다귀 전골 (대)', price: '35,000원' },
      { name: '뼈다귀 전골 (소)', price: '25,000원' },
      { name: '우거지 해장국', price: '9,000원' },
    ],
    info: '1블록 좌측외열 2번 · 11:00 ~ 22:00',
    rating: 4.6,
    badgeText: '식',
    block: 1,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '3',
    name: '좋은축산마을',
    category: '수산·정육',
    subCategory: '정육',
    hours: '09:00~21:00',
    description: '신선하고 엄선된 최고급 육류를 판매하는 정육점입니다.',
    isFood: true,
    tags: ['한우', '삼겹살', '정육'],
    info: '1블록 좌측외열 3번 · 09:00 ~ 21:00',
    rating: 4.7,
    badgeText: '육',
    block: 1,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '4',
    name: '해피브레드',
    category: '떡·빵·간식',
    subCategory: '식빵',
    hours: '08:00~21:00',
    description: '다양하고 건강한 수제 빵을 굽는 따뜻한 동네 빵집입니다.',
    isFood: false,
    tags: ['빵집', '식빵', '간식'],
    info: '1블록 좌측외열 4번 · 08:00 ~ 21:00',
    rating: 4.5,
    badgeText: '빵',
    block: 1,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '5',
    name: '잠실김밥',
    category: '음식',
    subCategory: '김밥',
    hours: '07:00~20:00',
    description: '속이 꽉 찬 수제 김밥과 다양한 분식 메뉴를 제공합니다.',
    isFood: true,
    tags: ['김밥', '라면', '떡볶이'],
    menus: [
      { name: '원조 김밥', price: '3,500원' },
      { name: '참치 마요 김밥', price: '4,500원' },
      { name: '치즈 라면', price: '4,500원' },
      { name: '라볶이 정식', price: '6,000원' },
    ],
    info: '1블록 좌측외열 5번 · 07:00 ~ 20:00',
    rating: 4.4,
    badgeText: '밥',
    block: 1,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '6',
    name: '알파디씨마트',
    category: '생활·서비스',
    subCategory: '잡화',
    hours: '09:00~22:00',
    description: '다양한 생활잡화와 편리한 도구를 저렴한 가격에 판매합니다.',
    isFood: false,
    tags: ['잡화', 'DC마트', '다양한'],
    info: '1블록 좌측외열 6번 · 09:00 ~ 22:00',
    rating: 4.3,
    badgeText: '생',
    block: 1,
    column: 'leftOuter',
    span: 2,
  },
  {
    id: '7',
    name: '새마을천막사(서울텐트)',
    category: '생활·서비스',
    subCategory: '천막',
    hours: '08:00~19:00',
    description: '천막 시공과 텐트, 방수 가림막을 전문으로 제작합니다.',
    isFood: false,
    tags: ['천막', '텐트', '제작'],
    info: '1블록 좌측외열 7번 · 08:00 ~ 19:00',
    rating: 4.5,
    badgeText: '생',
    block: 1,
    column: 'leftOuter',
    span: 2,
  },
  {
    id: '8',
    name: '코끼리약국',
    category: '생활·서비스',
    subCategory: '약국',
    hours: '09:00~21:00',
    description: '친절하고 상세한 복약 지도를 해드리는 동네 약국입니다.',
    isFood: false,
    tags: ['약국', '처방전', '상비약'],
    info: '1블록 좌측내열 8번 · 09:00 ~ 21:00',
    rating: 4.8,
    badgeText: '약',
    block: 1,
    column: 'leftInner',
    span: 2,
  },
  {
    id: '9',
    name: '남서울반찬',
    category: '반찬·식재료',
    subCategory: '반찬',
    hours: '09:00~20:00',
    description: '맛깔나고 정갈하게 만든 건강한 가정식 밑반찬입니다.',
    isFood: true,
    tags: ['반찬', '김치', '가정식'],
    info: '1블록 좌측내열 9번 · 09:00 ~ 20:00',
    rating: 4.6,
    badgeText: '반',
    block: 1,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '10',
    name: '명성왕족발',
    category: '음식',
    subCategory: '족발',
    hours: '12:00~23:00',
    description: '야들야들하고 부드러운 한방 족발 전문 맛집입니다.',
    isFood: true,
    tags: ['족발', '불족발', '보쌈'],
    menus: [
      { name: '한방 왕족발 (대)', price: '32,000원' },
      { name: '한방 왕족발 (중)', price: '28,000원' },
      { name: '매콤 양념 불족발', price: '22,000원' },
    ],
    info: '1블록 좌측내열 10번 · 12:00 ~ 23:00',
    rating: 4.7,
    badgeText: '음',
    block: 1,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '11',
    name: '민영활어공장',
    category: '수산·정육',
    subCategory: '초밥',
    hours: '09:00~20:00',
    description: '싱싱한 활어로 만든 스시와 회 포장 전문 매장입니다.',
    isFood: true,
    tags: ['초밥', '활어회', '포장'],
    menus: [
      { name: '민영 모듬초밥 (12p)', price: '15,000원' },
      { name: '특선 광어/연어초밥', price: '18,000원' },
      { name: '실속 활어 모듬회', price: '25,000원' },
    ],
    info: '1블록 좌측내열 11번 · 09:00 ~ 20:00',
    rating: 4.8,
    badgeText: '회',
    block: 1,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '12',
    name: '바다한스푼-어사또',
    category: '수산·정육',
    subCategory: '횟집',
    hours: '11:00~23:00',
    description: '산지직송 싱싱한 해산물과 활어회를 맛보실 수 있습니다.',
    isFood: false,
    tags: ['횟집', '해산물', '소주안주'],
    info: '1블록 좌측내열 12번 · 11:00 ~ 23:00',
    rating: 4.5,
    badgeText: '수',
    block: 1,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '13',
    name: '새마을순대국',
    category: '음식',
    subCategory: '순대국',
    hours: '09:00~21:00',
    description: '머리고기와 순대가 듬뿍 들어간 뜨끈하고 진한 순대국입니다.',
    isFood: false,
    tags: ['순대국', '국밥', '해장'],
    info: '1블록 좌측내열 13번 · 09:00 ~ 21:00',
    rating: 4.7,
    badgeText: '식',
    block: 1,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '14',
    name: '남서울건어물',
    category: '수산·정육',
    subCategory: '건어물',
    hours: '09:00~20:00',
    description: '좋은 품질의 국물용 멸치, 황태, 쥐포, 오징어가 가득합니다.',
    isFood: true,
    tags: ['건어물', '멸치', '쥐포'],
    info: '1블록 좌측내열 14번 · 09:00 ~ 20:00',
    rating: 4.4,
    badgeText: '수',
    block: 1,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '15',
    name: '우연 정육식당',
    category: '음식',
    subCategory: '고기집',
    hours: '11:00~22:00',
    description: '신선한 정육 부위를 즉석에서 구워 먹는 정육 식당입니다.',
    isFood: true,
    tags: ['한우', '삼겹살', '고기집'],
    info: '1블록 좌측내열 15번 · 11:00 ~ 22:00',
    rating: 4.6,
    badgeText: '음',
    block: 1,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '16',
    name: '남서울축산전문점',
    category: '수산·정육',
    subCategory: '정육',
    hours: '09:00~21:00',
    description: '신선한 한우와 한돈을 전문으로 도소매 판매합니다.',
    isFood: true,
    tags: ['정육', '국산고기', '신선'],
    info: '1블록 좌측내열 16번 · 09:00 ~ 21:00',
    rating: 4.5,
    badgeText: '육',
    block: 1,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '17',
    name: '생선파는 청년들',
    category: '수산·정육',
    subCategory: '생선',
    hours: '08:00~19:00',
    description: '청년들이 활기차게 운영하는 신선한 수산물/생선 가게입니다.',
    isFood: true,
    tags: ['생선', '수산물', '신선'],
    info: '1블록 좌측내열 17번 · 08:00 ~ 19:00',
    rating: 4.7,
    badgeText: '수',
    block: 1,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '18',
    name: '미남생선',
    category: '수산·정육',
    subCategory: '생선',
    hours: '08:00~19:00',
    description: '매일 아침 경매해오는 신선하고 품질 좋은 생선 전문점입니다.',
    isFood: true,
    tags: ['생선', '수산물', '구이용'],
    info: '1블록 좌측내열 18번 · 08:00 ~ 19:00',
    rating: 4.4,
    badgeText: '수',
    block: 1,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '19',
    name: '땅스부대찌개',
    category: '반찬·식재료',
    subCategory: '밀키트',
    hours: '10:00~21:00',
    description: '간편하고 푸짐하게 즐길 수 있는 3인분 부대찌개 밀키트 전문점.',
    isFood: true,
    tags: ['부대찌개', '밀키트', '포장'],
    info: '1블록 우측내열 19번 · 10:00 ~ 21:00',
    rating: 4.8,
    badgeText: '반',
    block: 1,
    column: 'rightInner',
    span: 2,
  },
  {
    id: '20',
    name: '과일나라 과일천국',
    category: '농산물',
    subCategory: '과일',
    hours: '08:00~20:00',
    description: '당도 높고 신선한 전국 산지의 맛있는 과일을 판매합니다.',
    isFood: true,
    tags: ['과일', '제철과일', '달콤한'],
    info: '1블록 우측내열 20번 · 08:00 ~ 20:00',
    rating: 4.6,
    badgeText: '농',
    block: 1,
    column: 'rightInner',
    span: 2,
  },
  {
    id: '21',
    name: '대영신천지 꽃집',
    category: '생활·서비스',
    subCategory: '꽃집',
    hours: '09:00~20:00',
    description: '예쁜 꽃다발과 인테리어용 반려 식물, 화분을 다룹니다.',
    isFood: false,
    tags: ['꽃', '화분', '선물'],
    info: '1블록 우측내열 21번 · 09:00 ~ 20:00',
    rating: 4.5,
    badgeText: '생',
    block: 1,
    column: 'rightInner',
    span: 1,
  },

  // ═══ 블록 2 ═══
  {
    id: '22',
    name: '오렌지분식',
    category: '음식',
    subCategory: '떡볶이',
    hours: '10:00~22:00',
    description: '떡볶이와 순대 맛집입니다.',
    isFood: true,
    tags: ['떡볶이', '분식', '순대'],
    menus: [
      { name: '떡볶이', price: '4,000원' },
      { name: '순대', price: '4,500원' },
      { name: '모듬튀김 (5개)', price: '4,000원' },
      { name: '오뎅 (3개)', price: '3,000원' },
    ],
    info: '2블록 우측내열 22번 · 10:00 ~ 22:00',
    rating: 4.8,
    badgeText: '분',
    block: 2,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '23',
    name: '두란노커피',
    category: '음식',
    subCategory: '카페',
    hours: '08:00~21:00',
    description: '향긋한 로스팅 커피 전문점.',
    isFood: false,
    tags: ['커피', '아메리카노', '카페'],
    info: '2블록 우측내열 23번 · 08:00 ~ 21:00',
    rating: 4.6,
    badgeText: '차',
    block: 2,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '24',
    name: '고향전집',
    category: '음식',
    subCategory: '전집',
    hours: '11:00~22:00',
    description: '고소한 부침개 전문점.',
    isFood: false,
    tags: ['전', '동그랑땡', '막걸리'],
    info: '2블록 우측내열 24번 · 11:00 ~ 22:00',
    rating: 4.5,
    badgeText: '전',
    block: 2,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '25',
    name: '생선파는 청년들',
    category: '수산·정육',
    subCategory: '생선',
    hours: '08:00~19:00',
    description: '2블록 우측내열의 신선한 생선 가게.',
    isFood: false,
    tags: ['생선', '갈치', '신선'],
    info: '2블록 우측내열 25번 · 08:00 ~ 19:00',
    rating: 4.7,
    badgeText: '수',
    block: 2,
    column: 'rightInner',
    span: 2,
  },
  {
    id: '26',
    name: '강남지물',
    category: '생활·서비스',
    subCategory: '도배',
    hours: '08:00~19:00',
    description: '도배, 장판 시공 전문.',
    isFood: false,
    tags: ['지물포', '인테리어', '도배'],
    info: '2블록 우측내열 26번 · 08:00 ~ 19:00',
    rating: 4.4,
    badgeText: '생',
    block: 2,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '27',
    name: '칼라분식',
    category: '음식',
    subCategory: '떡볶이',
    hours: '10:00~22:00',
    description: '바삭한 튀김과 떡볶이가 맛있는 분식점.',
    isFood: false,
    tags: ['떡볶이', '튀김범벅', '수제튀김'],
    info: '2블록 우측내열 27번 · 10:00 ~ 22:00',
    rating: 4.9,
    badgeText: '분',
    block: 2,
    column: 'rightInner',
    span: 2,
  },
  {
    id: '28',
    name: '자연애곳간',
    category: '반찬·식재료',
    subCategory: '반찬',
    hours: '09:00~20:00',
    description: '맛있는 김치와 건강한 반찬가게.',
    isFood: false,
    tags: ['반찬', '김치', '친환경'],
    info: '2블록 우측외열 28번 · 09:00 ~ 20:00',
    rating: 4.5,
    badgeText: '반',
    block: 2,
    column: 'rightOuter',
    span: 1,
  },
  {
    id: '29',
    name: '대성정육점',
    category: '수산·정육',
    subCategory: '정육',
    hours: '09:00~21:00',
    description: '신선한 정육 고기를 제공합니다.',
    isFood: true,
    tags: ['한돈', '한우', '삼겹살'],
    info: '2블록 우측외열 29번 · 09:00 ~ 21:00',
    rating: 4.7,
    badgeText: '육',
    block: 2,
    column: 'rightOuter',
    span: 2,
  },
  {
    id: '30',
    name: '명동이발',
    category: '생활·서비스',
    subCategory: '이발소',
    hours: '08:00~19:00',
    description: '깔끔하게 머리를 다듬어 드립니다.',
    isFood: false,
    tags: ['이발소', '헤어컷', '남성전문'],
    info: '2블록 우측외열 30번 · 08:00 ~ 19:00',
    rating: 4.3,
    badgeText: '생',
    block: 2,
    column: 'rightOuter',
    span: 1,
  },
  {
    id: '31',
    name: '상인회사무실',
    category: '생활·서비스',
    subCategory: '상인회',
    hours: '09:00~18:00',
    description: '시장 관리를 돕는 상인회 사무실입니다.',
    isFood: false,
    tags: ['상인회', '사무실', '행정'],
    info: '2블록 우측외열 31번 · 09:00 ~ 18:00',
    rating: 4.6,
    badgeText: '정',
    block: 2,
    column: 'rightOuter',
    span: 4,
  },

  // ═══ 블록 3 ═══
  {
    id: '32',
    name: '신천포차',
    category: '음식',
    subCategory: '포차',
    hours: '16:00~02:00',
    description: '술 한잔 기울이기 좋은 신천포차.',
    isFood: true,
    tags: ['포차', '소주안주', '야식'],
    menus: [
      { name: '대포 오뎅탕', price: '15,000원' },
      { name: '매콤 무뼈닭발', price: '16,000원' },
      { name: '가마솥 계란말이', price: '13,000원' },
    ],
    info: '3블록 좌측외열 32번 · 16:00 ~ 02:00',
    rating: 4.7,
    badgeText: '술',
    block: 3,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '33',
    name: '나눔상회',
    category: '생활·서비스',
    subCategory: '잡화',
    hours: '09:00~20:00',
    description: '알뜰한 생활 잡화 판매처.',
    isFood: false,
    tags: ['잡화', '생활용품', '알뜰'],
    info: '3블록 좌측외열 33번 · 09:00 ~ 20:00',
    rating: 4.4,
    badgeText: '생',
    block: 3,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '34',
    name: '생선구이·잠실새마을생선',
    category: '음식',
    subCategory: '생선구이',
    hours: '09:30~21:00',
    description:
      '노릇노릇하고 바삭하게 구워낸 맛있는 생선구이 정식 전문점입니다.',
    isFood: true,
    tags: ['생선구이', '고등어구이', '식사'],
    menus: [
      { name: '모듬 생선구이 정식', price: '12,000원' },
      { name: '고등어 구이', price: '9,000원' },
      { name: '갈치 조림 (2인)', price: '22,000원' },
    ],
    info: '3블록 좌측외열 34번 · 09:30 ~ 21:00',
    rating: 4.7,
    badgeText: '식',
    block: 3,
    column: 'leftOuter',
    span: 1,
  },

  {
    id: '35',
    name: '강경상회',
    category: '반찬·식재료',
    subCategory: '반찬',
    hours: '09:00~20:00',
    description: '강경 젓갈 전문점입니다.',
    isFood: false,
    tags: ['젓갈', '명란젓', '반찬'],
    info: '3블록 좌측내열 35번 · 09:00 ~ 20:00',
    rating: 4.8,
    badgeText: '반',
    block: 3,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '36',
    name: '늘푸른야채가게',
    category: '농산물',
    subCategory: '야채',
    hours: '08:00~20:00',
    description: '싱싱한 제철 야채와 농산물.',
    isFood: false,
    tags: ['채소', '야채', '신선식재료'],
    info: '3블록 좌측내열 36번 · 08:00 ~ 20:00',
    rating: 4.5,
    badgeText: '농',
    block: 3,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '37',
    name: '마을축산',
    category: '수산·정육',
    subCategory: '정육',
    hours: '09:00~21:00',
    description: '신선한 생고기와 육류 고기.',
    isFood: true,
    tags: ['생고기', '한우', '삼겹살'],
    info: '3블록 좌측내열 37번 · 09:00 ~ 21:00',
    rating: 4.7,
    badgeText: '육',
    block: 3,
    column: 'leftInner',
    span: 2,
  },
  {
    id: '38',
    name: '싱싱한과일(풍선생선)',
    category: '농산물',
    subCategory: '과일',
    hours: '08:00~20:00',
    description: '맛있고 달콤한 과일나라.',
    isFood: true,
    tags: ['제철과일', '청과', '과일천국'],
    info: '3블록 좌측내열 38번 · 08:00 ~ 20:00',
    rating: 4.4,
    badgeText: '농',
    block: 3,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '39',
    name: '새내방앗간',
    category: '떡·빵·간식',
    subCategory: '참기름',
    hours: '08:00~20:00',
    description: '고소한 참기름 방앗간.',
    isFood: true,
    tags: ['참기름', '들기름', '고춧가루'],
    info: '3블록 우측내열 39번 · 08:00 ~ 20:00',
    rating: 4.8,
    badgeText: '간',
    block: 3,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '40',
    name: '새마을지물포',
    category: '생활·서비스',
    subCategory: '도배',
    hours: '08:00~19:00',
    description: '인테리어 지물 도배 전문.',
    isFood: false,
    tags: ['지물포', '도배', '장판'],
    info: '3블록 우측내열 40번 · 08:00 ~ 19:00',
    rating: 4.5,
    badgeText: '생',
    block: 3,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '41',
    name: '행복전집',
    category: '음식',
    subCategory: '전집',
    hours: '11:00~22:00',
    description: '노릇한 녹두빈대떡과 모듬전.',
    isFood: false,
    tags: ['부침개', '빈대떡', '명절전'],
    info: '3블록 우측내열 41번 · 11:00 ~ 22:00',
    rating: 4.7,
    badgeText: '전',
    block: 3,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '42',
    name: '명가떡집',
    category: '떡·빵·간식',
    subCategory: '떡집',
    hours: '07:30~20:30',
    description: '쫄깃한 전통 시루떡과 찰떡.',
    isFood: true,
    tags: ['시루떡', '꿀떡', '송편'],
    menus: [
      { name: '꿀떡 (1팩)', price: '3,000원' },
      { name: '시루떡 (1팩)', price: '3,500원' },
      { name: '오색 바람떡 (1팩)', price: '3,000원' },
      { name: '영양 찰떡 (5개)', price: '6,000원' },
    ],
    info: '3블록 우측내열 42번 · 07:30 ~ 20:30',
    rating: 4.9,
    badgeText: '떡',
    block: 3,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '43',
    name: '박가네두부',
    category: '반찬·식재료',
    subCategory: '두부',
    hours: '08:00~20:00',
    description: '매일 아침 만드는 따끈한 가마솥 손두부.',
    isFood: true,
    tags: ['손두부', '콩물', '도토리묵'],
    info: '3블록 우측내열 43번 · 08:00 ~ 20:00',
    rating: 4.8,
    badgeText: '두',
    block: 3,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '44',
    name: '강동참기름',
    category: '반찬·식재료',
    subCategory: '참기름',
    hours: '08:30~20:00',
    description: '고소함이 깊은 참기름 전문점.',
    isFood: false,
    tags: ['참기름', '들기름', '전통곡물'],
    info: '3블록 우측내열 44번 · 08:30 ~ 20:00',
    rating: 4.6,
    badgeText: '유',
    block: 3,
    column: 'rightInner',
    span: 1,
  },

  // ═══ 블록 4 ═══
  {
    id: '45',
    name: '천수횟집',
    category: '수산·정육',
    subCategory: '횟집',
    hours: '11:00~23:00',
    description: '광어, 우럭 신선회 포장.',
    isFood: true,
    tags: ['횟집', '광어회', '회포장'],
    info: '4블록 좌측외열 45번 · 11:00 ~ 23:00',
    rating: 4.7,
    badgeText: '회',
    block: 4,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '46',
    name: '잠실생삼겹살',
    category: '음식',
    subCategory: '삼겹살',
    hours: '12:00~23:00',
    description: '노릇한 생삼겹살 맛집.',
    isFood: false,
    tags: ['삼겹살', '생삼겹', '식사'],
    info: '4블록 좌측외열 46번 · 12:00 ~ 23:00',
    rating: 4.6,
    badgeText: '음',
    block: 4,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '47',
    name: '포도마당',
    category: '음식',
    subCategory: '포차',
    hours: '17:00~02:00',
    description: '닭발과 먹태 맛있는 한잔 대포집.',
    isFood: false,
    tags: ['실내포차', '소주', '안주'],
    info: '4블록 좌측외열 47번 · 17:00 ~ 02:00',
    rating: 4.4,
    badgeText: '술',
    block: 4,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '48',
    name: '팥단지',
    category: '음식',
    subCategory: '단팥죽',
    hours: '10:00~21:00',
    description: '가마솥에 쑤어 달콤 고소한 단팥죽.',
    isFood: true,
    tags: ['팥죽', '단팥죽', '국산팥'],
    menus: [
      { name: '가마솥 단팥죽', price: '7,000원' },
      { name: '옛날 팥빙수', price: '8,000원' },
      { name: '단팥 찐빵 (2개)', price: '3,000원' },
    ],
    info: '4블록 좌측외열 48번 · 10:00 ~ 21:00',
    rating: 4.8,
    badgeText: '단',
    block: 4,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '49',
    name: '서울축산',
    category: '수산·정육',
    subCategory: '정육',
    hours: '09:00~21:00',
    description: '최고급 투뿔 등급 한우 정육점.',
    isFood: true,
    tags: ['한우', '생고기', '정육'],
    info: '4블록 좌측내열 49번 · 09:00 ~ 21:00',
    rating: 4.7,
    badgeText: '육',
    block: 4,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '50',
    name: '서울떡집',
    category: '떡·빵·간식',
    subCategory: '떡집',
    hours: '07:00~20:00',
    description: '전통 잔치 영양 떡 맞춤 전문 떡집.',
    isFood: true,
    tags: ['찰떡', '인절미', '영양떡'],
    info: '4블록 좌측내열 50번 · 07:00 ~ 20:00',
    rating: 4.5,
    badgeText: '떡',
    block: 4,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '51',
    name: '미소담찬',
    category: '반찬·식재료',
    subCategory: '반찬',
    hours: '09:00~20:30',
    description: '정성껏 만드는 밑반찬 전문 맛집.',
    isFood: false,
    tags: ['반찬', '조림반찬', '나물류'],
    info: '4블록 좌측내열 51번 · 09:00 ~ 20:30',
    rating: 4.8,
    badgeText: '반',
    block: 4,
    column: 'leftInner',
    span: 2,
  },
  {
    id: '52',
    name: '매일야채',
    category: '농산물',
    subCategory: '야채',
    hours: '08:00~20:00',
    description: '손질되어 요리하기 편한 제철 야채 전문.',
    isFood: false,
    tags: ['신선야채', '뿌리채소', '나물'],
    info: '4블록 좌측내열 52번 · 08:00 ~ 20:00',
    rating: 4.6,
    badgeText: '농',
    block: 4,
    column: 'leftInner',
    span: 3,
  },
  {
    id: '53',
    name: '중앙청과',
    category: '농산물',
    subCategory: '과일',
    hours: '08:00~20:00',
    description: '당도 보장 사과, 귤 명품 청과가게.',
    isFood: true,
    tags: ['사과', '딸기', '과일상자'],
    info: '4블록 우측내열 53번 · 08:00 ~ 20:00',
    rating: 4.5,
    badgeText: '농',
    block: 4,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '54',
    name: '와구이닭',
    category: '음식',
    subCategory: '치킨',
    hours: '12:00~23:00',
    description: '바삭하고 든든한 가마솥 통닭.',
    isFood: true,
    tags: ['통닭', '기름기뺀', '치킨'],
    info: '4블록 우측내열 54번 · 12:00 ~ 23:00',
    rating: 4.7,
    badgeText: '닭',
    block: 4,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '55',
    name: '맛사랑전집',
    category: '음식',
    subCategory: '전집',
    hours: '11:00~22:00',
    description: '육전, 고추전, 동태전 모듬전 전문 맛집.',
    isFood: false,
    tags: ['모듬전', '육전', '안주'],
    info: '4블록 우측내열 55번 · 11:00 ~ 22:00',
    rating: 4.6,
    badgeText: '전',
    block: 4,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '56',
    name: '쌍둥이네 수제한과',
    category: '떡·빵·간식',
    subCategory: '한과',
    hours: '09:00~20:00',
    description: '바삭한 오란다와 한과 맛집.',
    isFood: false,
    tags: ['한과', '오란다', '전통과자'],
    info: '4블록 우측내열 56번 · 09:00 ~ 20:00',
    rating: 4.8,
    badgeText: '과',
    block: 4,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '57',
    name: '명가왕만두',
    category: '음식',
    subCategory: '만두',
    hours: '09:00~21:00',
    description: '얇은 피의 수제 만두와 따끈한 찐빵 전문.',
    isFood: false,
    tags: ['만두', '왕만두', '찐빵'],
    info: '4블록 우측내열 57번 · 09:00 ~ 21:00',
    rating: 4.9,
    badgeText: '만',
    block: 4,
    column: 'rightInner',
    span: 2,
  },

  // ═══ 블록 5 ═══
  {
    id: '58',
    name: '새마을농산',
    category: '농산물',
    subCategory: '야채',
    hours: '08:00~20:00',
    description: '국산 검은 콩, 보리, 쌀 잡곡류 도매.',
    isFood: false,
    tags: ['잡곡', '현미', '농산'],
    info: '5블록 좌측내열 58번 · 08:00 ~ 20:00',
    rating: 4.5,
    badgeText: '농',
    block: 5,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '59',
    name: '보금당',
    category: '생활·서비스',
    subCategory: '주얼리',
    hours: '10:00~19:30',
    description: '명품 귀금속 주얼리 감정 및 판매.',
    isFood: false,
    tags: ['금은방', '시계수리', '주얼리'],
    info: '5블록 좌측내열 59번 · 10:00 ~ 19:30',
    rating: 4.7,
    badgeText: '생',
    block: 5,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '60',
    name: '박가네 두부',
    category: '반찬·식재료',
    subCategory: '두부',
    hours: '08:00~20:00',
    description: '두부와 도토리묵 건강 먹거리집.',
    isFood: false,
    tags: ['두부', '순두부', '도토리묵'],
    info: '5블록 좌측내열 60번 · 08:00 ~ 20:00',
    rating: 4.8,
    badgeText: '두',
    block: 5,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '61',
    name: '다모아패션',
    category: '의류',
    subCategory: '의류',
    hours: '10:00~20:00',
    description: '여성 데일리 캐주얼 생활웨어.',
    isFood: false,
    tags: ['의류', '몸빼바지', '패션'],
    info: '5블록 좌측내열 61번 · 10:00 ~ 20:00',
    rating: 4.3,
    badgeText: '의',
    block: 5,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '62',
    name: '우리청과',
    category: '농산물',
    subCategory: '과일',
    hours: '08:00~20:00',
    description: '수입 망고, 오렌지 및 명품 과일 상자 선물.',
    isFood: false,
    tags: ['과일', '선물세트', '청과'],
    info: '5블록 좌측내열 62번 · 08:00 ~ 20:00',
    rating: 4.6,
    badgeText: '농',
    block: 5,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '63',
    name: '우리한우 곰탕',
    category: '음식',
    subCategory: '곰탕',
    hours: '10:00~21:30',
    description: '깊고 맑게 고아낸 한우 가마솥 곰탕 맛집.',
    isFood: true,
    tags: ['곰탕', '수육', '국밥'],
    info: '5블록 우측내열 63번 · 10:00 ~ 21:30',
    rating: 4.8,
    badgeText: '국',
    block: 5,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '64',
    name: '대보선식',
    category: '반찬·식재료',
    subCategory: '선식',
    hours: '09:00~20:00',
    description: '건강 선식 미숫가루 전문 조제.',
    isFood: false,
    tags: ['선식', '미숫가루', '건강식'],
    info: '5블록 우측내열 64번 · 09:00 ~ 20:00',
    rating: 4.7,
    badgeText: '곡',
    block: 5,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '65',
    name: '기섭이네생선가게',
    category: '수산·정육',
    subCategory: '생선',
    hours: '08:00~19:00',
    description: '조기와 굴비 등 간이 잘 맞춘 생선.',
    isFood: false,
    tags: ['생선', '수산물', '조기'],
    info: '5블록 우측내열 65번 · 08:00 ~ 19:00',
    rating: 4.5,
    badgeText: '수',
    block: 5,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '66',
    name: '별콩 다방',
    category: '음식',
    subCategory: '카페',
    hours: '08:30~21:00',
    description: '달달한 옛날 다방 커피와 시원한 미숫가루 스무디.',
    isFood: false,
    tags: ['커피', '전통차', '빙수'],
    info: '5블록 우측내열 66번 · 08:30 ~ 21:00',
    rating: 4.4,
    badgeText: '차',
    block: 5,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '67',
    name: '깻잎닭강정',
    category: '음식',
    subCategory: '치킨',
    hours: '11:00~22:30',
    description: '깻잎이 들어가 향긋한 양념 닭강정 전문.',
    isFood: false,
    tags: ['닭강정', '치킨', '간식'],
    info: '5블록 우측내열 67번 · 11:00 ~ 22:30',
    rating: 4.9,
    badgeText: '닭',
    block: 5,
    column: 'rightInner',
    span: 1,
  },

  // ═══ 블록 6 ═══
  {
    id: '68',
    name: '정민식품',
    category: '반찬·식재료',
    subCategory: '두부',
    hours: '08:00~20:00',
    description: '수제 묵과 웰빙 두부 판매가게.',
    isFood: false,
    tags: ['두부', '도토리묵', '웰빙'],
    info: '6블록 좌측외열 68번 · 08:00 ~ 20:00',
    rating: 4.6,
    badgeText: '두',
    block: 6,
    column: 'leftOuter',
    span: 1,
  },
  {
    id: '69',
    name: '곱창과 순댓국',
    category: '음식',
    subCategory: '순대국',
    hours: '10:00~22:00',
    description: '불 맛 가득 야채 곱창과 뜨끈한 순대국국밥.',
    isFood: false,
    tags: ['순대국', '야채곱창', '국밥'],
    info: '6블록 좌측내열 69번 · 10:00 ~ 22:00',
    rating: 4.7,
    badgeText: '곱',
    block: 6,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '70',
    name: '장충동족발',
    category: '음식',
    subCategory: '족발',
    hours: '12:00~23:30',
    description: '야들야들하고 부드러운 정통 왕족발 맛집.',
    isFood: true,
    tags: ['족발', '장충동', '야식'],
    info: '6블록 좌측내열 70번 · 12:00 ~ 23:30',
    rating: 4.8,
    badgeText: '족',
    block: 6,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '71',
    name: '맥반석 김',
    category: '반찬·식재료',
    subCategory: '즉석 ',
    hours: '08:30~20:00',
    description: '맥반석 화덕에 구워 고소하고 짭조롬한 김.',
    isFood: false,
    tags: ['김구이', '맥반석김', '밑반찬'],
    info: '6블록 좌측내열 71번 · 08:30 ~ 20:00',
    rating: 4.9,
    badgeText: '김',
    block: 6,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '72',
    name: '오복떡방앗간',
    category: '떡·빵·간식',
    subCategory: '가래떡',
    hours: '07:00~20:00',
    description: '명절 떡 방앗간 가래떡 전문.',
    isFood: false,
    tags: ['방앗간', '가래떡', '찰떡'],
    info: '6블록 좌측내열 72번 · 07:00 ~ 20:00',
    rating: 4.7,
    badgeText: '떡',
    block: 6,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '73',
    name: '김자순 수제돈까스',
    category: '음식',
    subCategory: '돈까스',
    hours: '11:00~21:00',
    description: '바삭하게 즉석에서 튀겨 드리는 돈까스 전문.',
    isFood: true,
    tags: ['돈까스', '수제돈까스', '튀김'],
    info: '6블록 좌측내열 73번 · 11:00 ~ 21:00',
    rating: 4.6,
    badgeText: '가',
    block: 6,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '74',
    name: '명품치킨',
    category: '음식',
    subCategory: '치킨',
    hours: '12:00~23:30',
    description: '겉바속촉 가마솥 치킨 닭강정 전문.',
    isFood: true,
    tags: ['가마솥치킨', '닭강정', '맥주안주'],
    info: '6블록 우측내열 74번 · 12:00 ~ 23:30',
    rating: 4.8,
    badgeText: '닭',
    block: 6,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '75',
    name: '트라이쌍방울',
    category: '의류',
    subCategory: '이너웨어',
    hours: '09:00~20:00',
    description: '면 100% 전통 속옷 내의 할인매장.',
    isFood: false,
    tags: ['속옷', '내의', '트라이'],
    info: '6블록 우측내열 75번 · 09:00 ~ 20:00',
    rating: 4.4,
    badgeText: '의',
    block: 6,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '76',
    name: '공씨네 족발',
    category: '음식',
    subCategory: '족발',
    hours: '12:00~23:00',
    description: '푸짐하고 야들야들한 왕족발 전문.',
    isFood: false,
    tags: ['족발', '불족발', '인심'],
    info: '6블록 우측내열 76번 · 12:00 ~ 23:00',
    rating: 4.7,
    badgeText: '음',
    block: 6,
    column: 'rightInner',
    span: 3,
  },
  {
    id: '77',
    name: '반찬나라',
    category: '반찬·식재료',
    subCategory: '반찬',
    hours: '09:00~21:00',
    description: '매일 조리해 신선한 건강 밑반찬.',
    isFood: true,
    tags: ['밑반찬', '조림', '가성비반찬'],
    info: '6블록 우측내열 77번 · 09:00 ~ 21:00',
    rating: 4.5,
    badgeText: '반',
    block: 6,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '78',
    name: '민속보리밥',
    category: '음식',
    subCategory: '보리밥',
    hours: '10:30~20:30',
    description: '신선한 야채와 참기름 비빔 보리밥.',
    isFood: true,
    tags: ['보리밥', '제육', '비빔밥'],
    info: '6블록 우측외열 78번 · 10:30 ~ 20:30',
    rating: 4.6,
    badgeText: '식',
    block: 6,
    column: 'rightOuter',
    span: 2,
  },

  // ═══ 블록 7 ═══
  {
    id: '79',
    name: '호주뉴질랜드건강면세점',
    category: '생활·서비스',
    subCategory: '건강기',
    hours: '10:00~19:00',
    description: '부모님 선물용 명품 오메가3 영양제 매장.',
    isFood: false,
    tags: ['영양제', '프로폴리스', '선물'],
    info: '7블록 좌측내열 79번 · 10:00 ~ 19:00',
    rating: 4.4,
    badgeText: '생',
    block: 7,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '80',
    name: '도그버디애완용품',
    category: '생활·서비스',
    subCategory: '애견용품',
    hours: '10:00~21:00',
    description: '강아지와 고양이를 위한 애견 사료 간식샵.',
    isFood: false,
    tags: ['반려견', '애견사료', '강아지옷'],
    info: '7블록 좌측내열 80번 · 10:00 ~ 21:00',
    rating: 4.6,
    badgeText: '생',
    block: 7,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '81',
    name: '치킨박사',
    category: '음식',
    subCategory: '닭다리',
    hours: '12:00~23:00',
    description: '원하는 날개, 다리 부위 닭튀김 치킨 전문.',
    isFood: false,
    tags: ['후라이드', '닭다리', '맥주안주'],
    info: '7블록 좌측내열 81번 · 12:00 ~ 23:00',
    rating: 4.7,
    badgeText: '닭',
    block: 7,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '82',
    name: '동양식품',
    category: '반찬·식재료',
    subCategory: '국수소면',
    hours: '08:30~20:00',
    description: '마른 반찬거리 및 각종 조미료 양념 전문 마트.',
    isFood: false,
    tags: ['식자재', '양념류', '식품도매'],
    info: '7블록 좌측내열 82번 · 08:30 ~ 20:00',
    rating: 4.3,
    badgeText: '반',
    block: 7,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '83',
    name: '옛날산골바베큐',
    category: '음식',
    subCategory: '삼겹살',
    hours: '13:00~22:00',
    description: '회전 가마 훈제 삼겹살 바베큐 포장.',
    isFood: false,
    tags: ['바베큐', '훈제삼겹살', '포장'],
    info: '7블록 좌측내열 83번 · 13:00 ~ 22:00',
    rating: 4.8,
    badgeText: '구',
    block: 7,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '84',
    name: '속옷할인매장',
    category: '의류',
    subCategory: '속옷',
    hours: '09:30~20:00',
    description: '부드러운 면 잠옷 속옷 할인샵.',
    isFood: false,
    tags: ['속옷', '양말', '할인'],
    info: '7블록 좌측내열 84번 · 09:30 ~ 20:00',
    rating: 4.5,
    badgeText: '의',
    block: 7,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '85',
    name: '주연식자재(농산물직판장)',
    category: '반찬·식재료',
    subCategory: '식자재',
    hours: '07:30~22:00',
    description: '대용량 마트 식자재 할인 도소매.',
    isFood: false,
    tags: ['식자재', '할인마트', '대량구매'],
    info: '7블록 우측내열 85번 · 07:30 ~ 22:00',
    rating: 4.5,
    badgeText: '반',
    block: 7,
    column: 'rightInner',
    span: 2,
  },
  {
    id: '86',
    name: '김반장 꼬마 김밥',
    category: '음식',
    subCategory: '김밥',
    hours: '08:00~20:00',
    description: '한입에 쏙 먹기 편한 꼬마 김밥과 분식.',
    isFood: false,
    tags: ['꼬마김밥', '어묵', '분식'],
    info: '7블록 우측내열 86번 · 08:00 ~ 20:00',
    rating: 4.7,
    badgeText: '김',
    block: 7,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '87',
    name: '서울찹쌀꽈배기',
    category: '떡·빵·간식',
    subCategory: '찹쌀 ',
    hours: '09:00~20:00',
    description: '달달 설탕의 쫄깃 꽈배기 전통 맛집.',
    isFood: true,
    tags: ['꽈배기', '찹쌀도너츠', '핫도그'],
    info: '7블록 우측내열 87번 · 09:00 ~ 20:00',
    rating: 4.8,
    badgeText: '과',
    block: 7,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '88',
    name: '족발미녀',
    category: '음식',
    subCategory: '족발',
    hours: '13:00~23:00',
    description: '직화 양념 구이 쫄깃한 미니 족발집.',
    isFood: true,
    tags: ['족발', '불족발', '안주'],
    info: '7블록 우측내열 88번 · 13:00 ~ 23:00',
    rating: 4.6,
    badgeText: '음',
    block: 7,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '89',
    name: '다미청과',
    category: '농산물',
    subCategory: '과일',
    hours: '08:00~20:00',
    description: '고품격 과일상자 포장 청과가게.',
    isFood: true,
    tags: ['과일', '청과', '명품과일'],
    info: '7블록 우측내열 89번 · 08:00 ~ 20:00',
    rating: 4.7,
    badgeText: '농',
    block: 7,
    column: 'rightInner',
    span: 1,
  },

  // ═══ 블록 8 ═══
  {
    id: '90',
    name: '파오파오',
    category: '음식',
    subCategory: '만두',
    hours: '11:00~20:30',
    description: '수제 딤섬과 얇은 피 만두 달인 맛집.',
    isFood: false,
    tags: ['새우만두', '만두달인', '생활의달인'],
    info: '8블록 좌측내열 90번 · 11:00 ~ 20:30',
    rating: 4.9,
    badgeText: '만',
    block: 8,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '91',
    name: '동천곱창',
    category: '음식',
    subCategory: '야채',
    hours: '13:00~23:30',
    description: '매콤달콤 신선 야채 곱창 볶음 명가.',
    isFood: false,
    tags: ['야채곱창', '순대볶음', '안주'],
    info: '8블록 좌측내열 91번 · 13:00 ~ 23:30',
    rating: 4.7,
    badgeText: '곱',
    block: 8,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '92',
    name: '잠실수구레닭발',
    category: '음식',
    subCategory: '수구레',
    hours: '15:00~01:00',
    description: '쫄깃한 무뼈 닭발과 화끈하게 매운 양념볶음.',
    isFood: true,
    tags: ['수구레', '닭발', '야식'],
    info: '8블록 좌측내열 92번 · 15:00 ~ 01:00',
    rating: 4.6,
    badgeText: '음',
    block: 8,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '93',
    name: '한모네순대',
    category: '음식',
    subCategory: '찹쌀순대',
    hours: '09:00~21:00',
    description: '속이 꽉 찬 당일 전통 찹쌀 순대집.',
    isFood: true,
    tags: ['순대', '토종순대', '간식'],
    info: '8블록 좌측내열 93번 · 09:00 ~ 21:00',
    rating: 4.5,
    badgeText: '순',
    block: 8,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '94',
    name: '나주왕대포',
    category: '음식',
    subCategory: '실내대',
    hours: '16:00~02:00',
    description: '막걸리와 고소한 빈대떡 대포집 식당.',
    isFood: false,
    tags: ['대포집', '막걸리', '전통안주'],
    info: '8블록 좌측내열 94번 · 16:00 ~ 02:00',
    rating: 4.4,
    badgeText: '술',
    block: 8,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '95',
    name: '청춘청과',
    category: '농산물',
    subCategory: '야채',
    hours: '08:00~20:00',
    description: '선물 상자용 당도 우수 명품 과일 전문.',
    isFood: true,
    tags: ['과일', '청과', '청춘'],
    info: '8블록 우측내열 95번 · 08:00 ~ 20:00',
    rating: 4.8,
    badgeText: '농',
    block: 8,
    column: 'rightInner',
    span: 2,
  },
  {
    id: '96',
    name: '조선육회',
    category: '음식',
    subCategory: '육회비',
    hours: '11:00~22:00',
    description: '신선한 생 우둔살 쫄깃한 고소 조선 육회.',
    isFood: true,
    tags: ['육회', '육회비빔밥', '신선생고기'],
    info: '8블록 우측내열 96번 · 11:00 ~ 22:00',
    rating: 4.9,
    badgeText: '육',
    block: 8,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '97',
    name: '정성가득 국수',
    category: '음식',
    subCategory: '잔치국수',
    hours: '09:30~20:30',
    description: '깊은 멸치 육수 비법 멸치국수 잔치국수.',
    isFood: false,
    tags: ['잔치국수', '비빔국수', '가성비맛집'],
    info: '8블록 우측내열 97번 · 09:30 ~ 20:30',
    rating: 4.7,
    badgeText: '면',
    block: 8,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '98',
    name: '홍코너 수제튀김',
    category: '음식',
    subCategory: '김말이',
    hours: '11:00~22:00',
    description: '바삭하게 수제로 튀기는 수제 튀김 분식전문.',
    isFood: false,
    tags: ['김말이', '수제튀김', '떡볶이'],
    info: '8블록 우측내열 98번 · 11:00 ~ 22:00',
    rating: 4.8,
    badgeText: '튀',
    block: 8,
    column: 'rightInner',
    span: 1,
  },

  // ═══ 블록 9 ═══
  {
    id: '99',
    name: '빈 점포',
    category: '생활·서비스',
    subCategory: '공실',
    hours: '00:00~24:00',
    description: '공실 상태의 빈 점포 구역입니다.',
    isFood: false,
    tags: ['임대', '입점대기', '공실'],
    info: '9블록 좌측내열 99번 · 24시간',
    rating: 3.0,
    badgeText: '공',
    block: 9,
    column: 'leftInner',
    span: 1,
    isVacant: true, // 빈점포용 식별 플래그
  },
  {
    id: '100',
    name: '큰나무 유통',
    category: '생활·서비스',
    subCategory: '유통',
    hours: '08:30~19:30',
    description: '가공식품 및 잡화류 박스 도소매 전문.',
    isFood: false,
    tags: ['유통', '도소매', '생활잡화'],
    info: '9블록 좌측내열 100번 · 08:30 ~ 19:30',
    rating: 4.4,
    badgeText: '유',
    block: 9,
    column: 'leftInner',
    span: 1,
  },
  {
    id: '101',
    name: '미처버린파닭',
    category: '음식',
    subCategory: '치킨',
    hours: '13:00~24:00',
    description: '겨자 소스 파채와 알싸 든든한 닭날개 순살 치킨.',
    isFood: true,
    tags: ['순살치킨', '파닭', '맥주'],
    info: '9블록 우측내열 101번 · 13:00 ~ 24:00',
    rating: 4.7,
    badgeText: '닭',
    block: 9,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '102',
    name: '이모네곱창',
    category: '음식',
    subCategory: '야채',
    hours: '13:00~23:30',
    description: '철판에 야채와 순대를 매콤 볶아주는 족발곱창 전문.',
    isFood: true,
    tags: ['야채곱창', '막창', '철판구이'],
    info: '9블록 우측내열 102번 · 13:00 ~ 23:30',
    rating: 4.8,
    badgeText: '곱',
    block: 9,
    column: 'rightInner',
    span: 1,
  },
  {
    id: '103',
    name: '새마을빨래방',
    category: '생활·서비스',
    subCategory: '빨래방',
    hours: '00:00~24:00',
    description: '무인 빨래방 건조기 대형 세탁기 구비.',
    isFood: false,
    tags: ['무인세탁', '코인빨래방', '24시'],
    info: '9블록 우측내열 103번 · 24시간 연중무휴',
    rating: 4.6,
    badgeText: '생',
    block: 9,
    column: 'rightInner',
    span: 2,
  },
]
