import { Store } from '../types/store'

export const DUMMY_STORES: Store[] = [
  // ═══ 블록 1 ═══
  {
    id: '1',
    name: 'BGT소금빵',
    category: '떡·빵·간식',
    hours: '10:00~20:00',
    isFood: true,
  },
  {
    id: '2',
    name: '모두뼈다귀',
    category: '음식',
    hours: '11:00~22:00',
    isFood: true,
  },
  {
    id: '3',
    name: '좋은축산마을',
    category: '수산·정육',
    hours: '09:00~21:00',
    isFood: true,
  },
  {
    id: '4',
    name: '해피브레드',
    category: '떡·빵·간식',
    hours: '08:00~21:00',
    isFood: false,
  },
  {
    id: '5',
    name: '잠실김밥',
    category: '음식',
    hours: '07:00~20:00',
    isFood: true,
  },
  {
    id: '6',
    name: '알파디씨마트',
    category: '생활·서비스',
    hours: '09:00~22:00',
    isFood: false,
  },
  {
    id: '7',
    name: '새마을천막사(서울텐트)',
    category: '생활·서비스',
    hours: '08:00~19:00',
    isFood: false,
  },
  {
    id: '8',
    name: '코끼리약국',
    category: '생활·서비스',
    hours: '09:00~21:00',
    isFood: false,
  },
  {
    id: '9',
    name: '남서울반찬',
    category: '반찬·식재료',
    hours: '09:00~20:00',
    isFood: true,
  },
  {
    id: '10',
    name: '명성왕족발',
    category: '음식',
    hours: '12:00~23:00',
    isFood: true,
  },
  {
    id: '11',
    name: '민영활어공장',
    category: '수산·정육',
    hours: '09:00~20:00',
    isFood: true,
  },
  {
    id: '12',
    name: '바다한스푼-어사또',
    category: '수산·정육',
    hours: '11:00~23:00',
    isFood: false,
  },
  {
    id: '13',
    name: '새마을순대국',
    category: '음식',
    hours: '09:00~21:00',
    isFood: false,
  },
  {
    id: '14',
    name: '남서울건어물',
    category: '수산·정육',
    hours: '09:00~20:00',
    isFood: true,
  },
  {
    id: '15',
    name: '우연 정육식당',
    category: '음식',
    hours: '11:00~22:00',
    isFood: true,
  },
  {
    id: '16',
    name: '남서울축산전문점',
    category: '수산·정육',
    hours: '09:00~21:00',
    isFood: true,
  },
  {
    id: '17',
    name: '생선파는 청년들',
    category: '수산·정육',
    hours: '08:00~19:00',
    isFood: true,
  },
  {
    id: '18',
    name: '미남생선',
    category: '수산·정육',
    hours: '08:00~19:00',
    isFood: true,
  },
  {
    id: '19',
    name: '땅스부대찌개',
    category: '반찬·식재료',
    hours: '10:00~21:00',
    isFood: true,
  },
  {
    id: '20',
    name: '과일나라 과일천국',
    category: '농산물',
    hours: '08:00~20:00',
    isFood: true,
  },
  {
    id: '21',
    name: '대영신천지 꽃집',
    category: '생활·서비스',
    hours: '09:00~20:00',
    isFood: false,
  },

  // ═══ 블록 2 ═══
  {
    id: '22',
    name: '오렌지분식',
    category: '음식',
    hours: '10:00~22:00',
    isFood: true,
  },
  {
    id: '23',
    name: '두란노커피',
    category: '음식',
    hours: '08:00~21:00',
    isFood: false,
  },
  {
    id: '24',
    name: '고향전집',
    category: '음식',
    hours: '11:00~22:00',
    isFood: false,
  },
  {
    id: '25',
    name: '생선파는 청년들',
    category: '수산·정육',
    hours: '08:00~19:00',
    isFood: false,
  },
  {
    id: '26',
    name: '강남지물',
    category: '생활·서비스',
    hours: '08:00~19:00',
    isFood: false,
  },
  {
    id: '27',
    name: '칼라분식',
    category: '음식',
    hours: '10:00~22:00',
    isFood: false,
  },
  {
    id: '28',
    name: '자연애곳간',
    category: '반찬·식재료',
    hours: '09:00~20:00',
    isFood: false,
  },
  {
    id: '29',
    name: '대성정육점',
    category: '수산·정육',
    hours: '09:00~21:00',
    isFood: true,
  },
  {
    id: '30',
    name: '명동이발',
    category: '생활·서비스',
    hours: '08:00~19:00',
    isFood: false,
  },
  {
    id: '31',
    name: '상인회사무실',
    category: '생활·서비스',
    hours: '09:00~18:00',
    isFood: false,
  },

  // ═══ 블록 3 ═══
  {
    id: '32',
    name: '신천포차',
    category: '음식',
    hours: '16:00~02:00',
    isFood: true,
  },
  {
    id: '33',
    name: '나눔상회',
    category: '생활·서비스',
    hours: '09:00~20:00',
    isFood: false,
  },
  {
    id: '34',
    name: '생선구이·잠실새마을생선',
    category: '음식',
    hours: '09:30~21:00',
    isFood: true,
  },

  {
    id: '35',
    name: '강경상회',
    category: '반찬·식재료',
    hours: '09:00~20:00',
    isFood: false,
  },
  {
    id: '36',
    name: '늘푸른야채가게',
    category: '농산물',
    hours: '08:00~20:00',
    isFood: false,
  },
  {
    id: '37',
    name: '마을축산',
    category: '수산·정육',
    hours: '09:00~21:00',
    isFood: true,
  },
  {
    id: '38',
    name: '싱싱한과일(풍선생선)',
    category: '농산물',
    hours: '08:00~20:00',
    isFood: true,
  },
  {
    id: '39',
    name: '새내방앗간',
    category: '떡·빵·간식',
    hours: '08:00~20:00',
    isFood: true,
  },
  {
    id: '40',
    name: '새마을지물포',
    category: '생활·서비스',
    hours: '08:00~19:00',
    isFood: false,
  },
  {
    id: '41',
    name: '행복전집',
    category: '음식',
    hours: '11:00~22:00',
    isFood: false,
  },
  {
    id: '42',
    name: '명가떡집',
    category: '떡·빵·간식',
    hours: '07:30~20:30',
    isFood: true,
  },
  {
    id: '43',
    name: '박가네두부',
    category: '반찬·식재료',
    hours: '08:00~20:00',
    isFood: true,
  },
  {
    id: '44',
    name: '강동참기름',
    category: '반찬·식재료',
    hours: '08:30~20:00',
    isFood: false,
  },

  // ═══ 블록 4 ═══
  {
    id: '45',
    name: '천수횟집',
    category: '수산·정육',
    hours: '11:00~23:00',
    isFood: true,
  },
  {
    id: '46',
    name: '잠실생삼겹살',
    category: '음식',
    hours: '12:00~23:00',
    isFood: false,
  },
  {
    id: '47',
    name: '포도마당',
    category: '음식',
    hours: '17:00~02:00',
    isFood: false,
  },
  {
    id: '48',
    name: '팥단지',
    category: '음식',
    hours: '10:00~21:00',
    isFood: true,
  },
  {
    id: '49',
    name: '서울축산',
    category: '수산·정육',
    hours: '09:00~21:00',
    isFood: true,
  },
  {
    id: '50',
    name: '서울떡집',
    category: '떡·빵·간식',
    hours: '07:00~20:00',
    isFood: true,
  },
  {
    id: '51',
    name: '미소담찬',
    category: '반찬·식재료',
    hours: '09:00~20:30',
    isFood: false,
  },
  {
    id: '52',
    name: '매일야채',
    category: '농산물',
    hours: '08:00~20:00',
    isFood: false,
  },
  {
    id: '53',
    name: '중앙청과',
    category: '농산물',
    hours: '08:00~20:00',
    isFood: true,
  },
  {
    id: '54',
    name: '와구이닭',
    category: '음식',
    hours: '12:00~23:00',
    isFood: true,
  },
  {
    id: '55',
    name: '맛사랑전집',
    category: '음식',
    hours: '11:00~22:00',
    isFood: false,
  },
  {
    id: '56',
    name: '쌍둥이네 수제한과',
    category: '떡·빵·간식',
    hours: '09:00~20:00',
    isFood: false,
  },
  {
    id: '57',
    name: '명가왕만두',
    category: '음식',
    hours: '09:00~21:00',
    isFood: false,
  },

  // ═══ 블록 5 ═══
  {
    id: '58',
    name: '새마을농산',
    category: '농산물',
    hours: '08:00~20:00',
    isFood: false,
  },
  {
    id: '59',
    name: '보금당',
    category: '생활·서비스',
    hours: '10:00~19:30',
    isFood: false,
  },
  {
    id: '60',
    name: '박가네 두부',
    category: '반찬·식재료',
    hours: '08:00~20:00',
    isFood: false,
  },
  {
    id: '61',
    name: '다모아패션',
    category: '의류',
    hours: '10:00~20:00',
    isFood: false,
  },
  {
    id: '62',
    name: '우리청과',
    category: '농산물',
    hours: '08:00~20:00',
    isFood: false,
  },
  {
    id: '63',
    name: '우리한우 곰탕',
    category: '음식',
    hours: '10:00~21:30',
    isFood: true,
  },
  {
    id: '64',
    name: '대보선식',
    category: '반찬·식재료',
    hours: '09:00~20:00',
    isFood: false,
  },
  {
    id: '65',
    name: '기섭이네생선가게',
    category: '수산·정육',
    hours: '08:00~19:00',
    isFood: false,
  },
  {
    id: '66',
    name: '별콩 다방',
    category: '음식',
    hours: '08:30~21:00',
    isFood: false,
  },
  {
    id: '67',
    name: '깻잎닭강정',
    category: '음식',
    hours: '11:00~22:30',
    isFood: false,
  },

  // ═══ 블록 6 ═══
  {
    id: '68',
    name: '정민식품',
    category: '반찬·식재료',
    hours: '08:00~20:00',
    isFood: false,
  },
  {
    id: '69',
    name: '곱창과 순댓국',
    category: '음식',
    hours: '10:00~22:00',
    isFood: false,
  },
  {
    id: '70',
    name: '장충동족발',
    category: '음식',
    hours: '12:00~23:30',
    isFood: true,
  },
  {
    id: '71',
    name: '맥반석 김',
    category: '반찬·식재료',
    hours: '08:30~20:00',
    isFood: false,
  },
  {
    id: '72',
    name: '오복떡방앗간',
    category: '떡·빵·간식',
    hours: '07:00~20:00',
    isFood: false,
  },
  {
    id: '73',
    name: '김자순 수제돈까스',
    category: '음식',
    hours: '11:00~21:00',
    isFood: true,
  },
  {
    id: '74',
    name: '명품치킨',
    category: '음식',
    hours: '12:00~23:30',
    isFood: true,
  },
  {
    id: '75',
    name: '트라이쌍방울',
    category: '의류',
    hours: '09:00~20:00',
    isFood: false,
  },
  {
    id: '76',
    name: '공씨네 족발',
    category: '음식',
    hours: '12:00~23:00',
    isFood: false,
  },
  {
    id: '77',
    name: '반찬나라',
    category: '반찬·식재료',
    hours: '09:00~21:00',
    isFood: true,
  },
  {
    id: '78',
    name: '민속보리밥',
    category: '음식',
    hours: '10:30~20:30',
    isFood: true,
  },

  // ═══ 블록 7 ═══
  {
    id: '79',
    name: '호주뉴질랜드건강면세점',
    category: '생활·서비스',
    hours: '10:00~19:00',
    isFood: false,
  },
  {
    id: '80',
    name: '도그버디애완용품',
    category: '생활·서비스',
    hours: '10:00~21:00',
    isFood: false,
  },
  {
    id: '81',
    name: '치킨박사',
    category: '음식',
    hours: '12:00~23:00',
    isFood: false,
  },
  {
    id: '82',
    name: '동양식품',
    category: '반찬·식재료',
    hours: '08:30~20:00',
    isFood: false,
  },
  {
    id: '83',
    name: '옛날산골바베큐',
    category: '음식',
    hours: '13:00~22:00',
    isFood: false,
  },
  {
    id: '84',
    name: '속옷할인매장',
    category: '의류',
    hours: '09:30~20:00',
    isFood: false,
  },
  {
    id: '85',
    name: '주연식자재(농산물직판장)',
    category: '반찬·식재료',
    hours: '07:30~22:00',
    isFood: false,
  },
  {
    id: '86',
    name: '김반장 꼬마 김밥',
    category: '음식',
    hours: '08:00~20:00',
    isFood: false,
  },
  {
    id: '87',
    name: '서울찹쌀꽈배기',
    category: '떡·빵·간식',
    hours: '09:00~20:00',
    isFood: true,
  },
  {
    id: '88',
    name: '족발미녀',
    category: '음식',
    hours: '13:00~23:00',
    isFood: true,
  },
  {
    id: '89',
    name: '다미청과',
    category: '농산물',
    hours: '08:00~20:00',
    isFood: true,
  },

  // ═══ 블록 8 ═══
  {
    id: '90',
    name: '파오파오',
    category: '음식',
    hours: '11:00~20:30',
    isFood: false,
  },
  {
    id: '91',
    name: '동천곱창',
    category: '음식',
    hours: '13:00~23:30',
    isFood: false,
  },
  {
    id: '92',
    name: '잠실수구레닭발',
    category: '음식',
    hours: '15:00~01:00',
    isFood: true,
  },
  {
    id: '93',
    name: '한모네순대',
    category: '음식',
    hours: '09:00~21:00',
    isFood: true,
  },
  {
    id: '94',
    name: '나주왕대포',
    category: '음식',
    hours: '16:00~02:00',
    isFood: false,
  },
  {
    id: '95',
    name: '청춘청과',
    category: '농산물',
    hours: '08:00~20:00',
    isFood: true,
  },
  {
    id: '96',
    name: '조선육회',
    category: '음식',
    hours: '11:00~22:00',
    isFood: true,
  },
  {
    id: '97',
    name: '정성가득 국수',
    category: '음식',
    hours: '09:30~20:30',
    isFood: false,
  },
  {
    id: '98',
    name: '홍코너 수제튀김',
    category: '음식',
    hours: '11:00~22:00',
    isFood: false,
  },

  // ═══ 블록 9 ═══
  {
    id: '99',
    name: '빈 점포',
    category: '생활·서비스',
    hours: '00:00~24:00',
    isFood: false,
    isVacant: true, // 빈점포용 식별 플래그
  },
  {
    id: '100',
    name: '큰나무 유통',
    category: '생활·서비스',
    hours: '08:30~19:30',
    isFood: false,
  },
  {
    id: '101',
    name: '미처버린파닭',
    category: '음식',
    hours: '13:00~24:00',
    isFood: true,
  },
  {
    id: '102',
    name: '이모네곱창',
    category: '음식',
    hours: '13:00~23:30',
    isFood: true,
  },
  {
    id: '103',
    name: '새마을빨래방',
    category: '생활·서비스',
    hours: '00:00~24:00',
    isFood: false,
  },
]
